### ISSUE TITLE
Recursive closure: call the closure in a new thread report an error

### ISSUE THREAD

**Issue by ZhouHansen** [Stebalien/tool-rs#10]
Things I want to implement is here : [playground](https://play.rust-lang.org/?gist=2b1d0a825c1512a40190994a05ac1f7d)

Here's the overview: I'm defining a `function A` which take a `function B` as parameter, again the `function B` take `function C` as parameter. I need to call the `function C` in a new thread, In this case using `&dyn` keyword for the inner function gives me an error:
```rust
    fn a(b: impl Fn(&dyn Fn() -> ()) -> ()) -> () {
     // ...
    } 
```
```shell
    error[E0277]: `dyn std::ops::Fn() ->()` cannot be shared between threads safely
```
I try the syntax like below, but this gives me an another error: 
```rust
    fn a(b: impl Fn(impl Fn() -> ()) -> ()) -> () {
     // ...
    }  
```
```shell
    error[E0666]: nested `impl Trait` is not allowed
     --> src/main.rs:2:21
      |
    2 |     fn a(b: impl Fn(impl Fn() -> ()) -> ()) -> () {
      |             --------^^^^^^^^^^^^^^^-------
      |             |       |
      |             |       nested `impl Trait` here
      |             outer `impl Trait`
```

**Comment by Stebalien** [comment]
Off the top of my head, I'm not sure how to do this. Unfortunately, I'm also pretty sure there's nothing this library can do to make this simpler.

**Comment by ZhouHansen** [comment]
Thanks for reviewing!

**Comment by ZhouHansen** [comment]
Using ` std::sync::Mutex` instead of `std::cell::Cell` may help solve it?
