### ISSUE TITLE
Adopt fix?

### ISSUE THREAD

**Issue by bluss** [Stebalien/tool-rs#2]
Maybe you want to adopt the fix combinator for recursive closures. http://bluss.github.io/arrayvec/doc/odds/fn.fix.html

It fits better here than in odds (odds is mostly collections oriented).

If I could do breaking changes to that api, the Fix type would have private fields. Also, maybe the name should change, I'm not sure.

I don't think Rust allows implementing something like it without using a reference to a trait object, like it does.

**Comment by Stebalien** [comment]
I'd kind of like to wait for `impl Trait` and use something like:

``` rust
#![feature(conservative_impl_trait)]
use std::cell::Cell;

fn fix<A, B, F>(f: F) -> impl Fn(A) -> B
    where F: Fn(&Fn(A)-> B, A) -> B
{
    move |a: A| {
        // Hopefully optimized away. Can probably use some unsafe magic to help the optimizer...
        let tmp_fn = |_: A| -> B { panic!() };
        let (fun_holder, fun);
        fun_holder = Cell::new(&tmp_fn as &Fn(A) -> B);
        fun = |ai: A| { f(fun_holder.get(), ai) };
        fun_holder.set(&fun as &Fn(A) -> B);
        f(fun_holder.get(), a)
    }
}


fn main() {
    let fib = fix(|f, x| if x == 0 || x == 1 {
        x
    } else {
        f(x - 1) + f(x - 2)
    });
    assert_eq!(120, fib(10));
}
```

**Comment by bluss** [comment]
Wow, that's nice.
