### ISSUE TITLE
Rename `flip` to make space for haskell like `flip`

### ISSUE THREAD

**Issue by bluss** [Stebalien/tool-rs#5]
flip can be a closure combinator (swaps the order of the arguments of a closure).

There's even a funky use case for it:

``` rust
#![feature(conservative_impl_trait)]

fn flip<F, A, B, R>(f: F) -> impl Fn(B, A) -> R
    where F: Fn(A, B) -> R
{
    move |a, b| f(b, a)
}

fn main() {
    let mut v = vec![1, 2, 3];

    flip(Vec::push)(v[0], &mut v);
    println!("{:?}", v);
}
```

[(playground)](https://play.rust-lang.org/?gist=f4dee92a77c1e6d311120899d13b9e94&version=nightly&backtrace=0)

**Comment by Stebalien** [comment]
Do you mind if I just get rid of the current `flip`? IMO, we want something a bit more generic.

**Comment by bluss** [comment]
go ahead

**Comment by bluss** [comment]
You should bump the 0.x version when you remove things. I guess it doesn't matter much this early when there are no(?) users, but it's what's expected later.

**Comment by Stebalien** [comment]
I know. I'm just being lazy for now. But yes, I should start doing that...

**Comment by bluss** [comment]
hehe. If a crate breaks in the woods..?
