### ISSUE TITLE
Should there be implementations for second and first with deref?

### ISSUE THREAD

**Issue by iopq** [Stebalien/tool-rs#6]
I currently have a use case where I had to define

```
fn second<'a, A, B: ?Sized>(&&(_, ref second): &&'a (A, B)) -> &'a B {
    second
}
```

this is because the `tool` definition doesn't have one for this case

is this a rare case or should it be handled by `tool`? Note that it does one level of deref as well

**Comment by Stebalien** [comment]
I think I can do that but what is your usecase exactly (so I make sure I add the right impl)?

**Comment by Stebalien** [comment]
Basically, I can make it such that an implementation on some `&T` implies an implementation on `&&T` (with the same output).

**Comment by iopq** [comment]
Here's my code:

https://bitbucket.org/iopq/fizzbuzz-in-rust/src/1022d020a66966cef374851805fa206e898b172b/src/lib.rs?at=master&fileviewer=file-view-default

I wanted to write it point-free style, but `.filter(apply(second, i))` requires this `second` implementation so I took `tool` out temporarily
