### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by bluss** [Stebalien/tool-rs#9]
Hi! If you don't mind, I volunteer to take over maintainership of the cargo crate for tool.

**Comment by Stebalien** [comment]
@bluss that would be great! Unfortunately, I haven't had much time to dedicate to my rust projects recently.

Thanks for the offer.

**Comment by bluss** [comment]
Nice to hear from you! In other news I'm proposing FusedIterator for stabilization as soon as I get around to it..

**Comment by bluss** [comment]
This issue can now be closed because it has been addressed since long. @Stebalien gave me access to tool, but since I asked I was also on a hiatus (back for now!), so I haven't done my part, yet..
